# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZYG46EvfE3kmt_7pyYSkTzMYor0Fy7S
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="KMeans Clustering App",
    page_icon="📊",
    layout="wide"
)

# -----------------------------
# Title Section
# -----------------------------
st.title("📊 KMeans Clustering Streamlit App")
st.subheader("Customer Segmentation using Age and Income")
st.markdown(
    """
    This app demonstrates **KMeans Clustering** on a dataset containing **Age** and **Income**.
    It also shows how **feature scaling** improves clustering results and uses the **Elbow Method**
    to help choose the optimal number of clusters.
    """
)

# -----------------------------
# Load Data
# -----------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("income.csv")
    return df

df = load_data()

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.header("⚙️ App Controls")
use_scaling = st.sidebar.checkbox("Apply Min-Max Scaling", value=True)
n_clusters = st.sidebar.slider("Select Number of Clusters", min_value=2, max_value=10, value=3)

# -----------------------------
# Show Dataset
# -----------------------------
st.markdown("---")
st.header("📁 Dataset Preview")
st.dataframe(df, use_container_width=True)

st.write("**Dataset Shape:**", df.shape)

# -----------------------------
# Raw Data Visualization
# -----------------------------
st.markdown("---")
st.header("📌 Raw Data Scatter Plot")

fig1, ax1 = plt.subplots(figsize=(8, 5))
ax1.scatter(df["Age"], df["Income($)"])
ax1.set_xlabel("Age")
ax1.set_ylabel("Income($)")
ax1.set_title("Age vs Income")
st.pyplot(fig1)

# -----------------------------
# Data Preparation
# -----------------------------
X = df[["Age", "Income($)"]].copy()

if use_scaling:
    scaler = MinMaxScaler()
    X[["Age", "Income($)"]] = scaler.fit_transform(X[["Age", "Income($)"]])
    st.success("Min-Max Scaling applied to Age and Income.")
else:
    st.info("Scaling not applied.")

# -----------------------------
# KMeans Clustering
# -----------------------------
st.markdown("---")
st.header("🤖 KMeans Clustering Result")

km = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
y_pred = km.fit_predict(X)

df_result = X.copy()
df_result["cluster"] = y_pred

# Cluster centers
centers = km.cluster_centers_

# Plot clusters
fig2, ax2 = plt.subplots(figsize=(8, 5))

colors = ["green", "red", "blue", "orange", "purple", "brown", "pink", "cyan", "black", "yellow"]

for i in range(n_clusters):
    cluster_data = df_result[df_result["cluster"] == i]
    ax2.scatter(
        cluster_data["Age"],
        cluster_data["Income($)"],
        color=colors[i % len(colors)],
        label=f"Cluster {i}"
    )

ax2.scatter(
    centers[:, 0],
    centers[:, 1],
    s=200,
    color="black",
    marker="*",
    label="Centroids"
)

ax2.set_xlabel("Age")
ax2.set_ylabel("Income($)")
ax2.set_title("KMeans Clustering")
ax2.legend()

st.pyplot(fig2)

# -----------------------------
# Clustered Data Table
# -----------------------------
st.subheader("Clustered Data")
st.dataframe(df_result, use_container_width=True)

# -----------------------------
# Elbow Method
# -----------------------------
st.markdown("---")
st.header("📉 Elbow Method")

sse = []
k_range = range(1, 11)

for k in k_range:
    model = KMeans(n_clusters=k, random_state=42, n_init=10)
    model.fit(X)
    sse.append(model.inertia_)

fig3, ax3 = plt.subplots(figsize=(8, 5))
ax3.plot(k_range, sse, marker="o")
ax3.set_xlabel("Number of Clusters (K)")
ax3.set_ylabel("Sum of Squared Error (SSE)")
ax3.set_title("Elbow Plot")
st.pyplot(fig3)

# -----------------------------
# Insights Section
# -----------------------------
st.markdown("---")
st.header("📘 Insights")
st.write("""
- **KMeans** groups similar data points into clusters.
- **Age** and **Income** are used here as features for segmentation.
- **Scaling** helps because KMeans is distance-based.
- The **Elbow Plot** helps determine the best number of clusters.
""")

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")
st.caption("Built with Streamlit • Machine Learning Demo App")